### ISSUE TITLE
Environment variables are the unresolved variables

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#3]
**Describe the bug**
Environment variables are the unresolved variables

**To Reproduce**
1. Create lambda with 1 env var
2. Create step function with that lambda
2. Log the `process.env`
3. Your env vars show up as the unresolved variable string. i.e. `${something}`. 

**Expected behavior**
It should show up as the real env var's value

**Additional context**
As noted [here](https://www.serverless.com/framework/docs/providers/aws/guide/plugins#serverless-instance):
> Note: Variable references in the serverless instance are not resolved before a Plugin's constructor is called, so if you need these, make sure to wait to access those from your hooks.

So we just need run the `injectEnvVars` on a certain hook when the env vars have been evaluated

**Comment by jefer590** [comment]
solved, thank you very much!
