### ISSUE TITLE
Add waitForTaskToken for lambdas

### ISSUE THREAD

**Issue by sam-n-johnston** [jefer590/serverless-offline-step-functions#5]
**Is your feature request related to a problem? Please describe.**
AWS describes a callback pattern to wait for another service [here](https://docs.aws.amazon.com/step-functions/latest/dg/connect-to-resource.html#connect-wait-token).

**Describe the solution you'd like**
I would like the above example given by AWS to work as expected. 

**Additional context**

**Comment by sam-n-johnston** [comment]
@jefer590 can you assign me this issue?

**Comment by jefer590** [comment]
@sam-n-johnston done

**Comment by sam-n-johnston** [comment]
I'll start working on this Tomorrow.

**Comment by sam-n-johnston** [comment]
Closed with #24.
