### ISSUE TITLE
Add 256 Kb Limit

### ISSUE THREAD

**Issue by jefer590** [jefer590/serverless-offline-step-functions#6]
**Is your feature request related to a problem? Please describe.**
Not really, to have a more accurate simulation, we need to add the payload limit validation per workflow
- 256 Kilobytes

**Describe the solution you'd like**
before the State Machine execution, assert the JSON size with the data limit and throw an error if so

**Describe alternatives you've considered**
none yet

**Additional context**
question... is the data limit also per Task?

**Comment by sam-n-johnston** [comment]
We should also check the docs of how AWS does this verification. How does it calculate the payload size?
